### ISSUE TITLE
dbviewer not able to connect to PostGIS database

### ISSUE THREAD

**Issue by lucadelu** [TheHortonMachine/hortonmachine#70]
I tried to connect to a local PostGIS database using `remote` button (this is the string I used in the URL jdbc:h2:tcp://localhost:5432/pollen) but it fail with this answer

~~~
Process Open database started at: 2021-11-09 11:50:42


ERROR:: :: Error connecting to the database...
java.sql.SQLException: Connections could not be acquired from the underlying database!
	at com.mchange.v2.sql.SqlUtils.toSQLException(SqlUtils.java:118)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool.checkoutPooledConnection(C3P0PooledConnectionPool.java:692)
	at com.mchange.v2.c3p0.impl.AbstractPoolBackedDataSource.getConnection(AbstractPoolBackedDataSource.java:140)
	at org.hortonmachine.dbs.h2gis.H2Db.getJdbcConnection(H2Db.java:173)
	at org.hortonmachine.dbs.h2gis.H2Db.getConnectionInternal(H2Db.java:180)
	at org.hortonmachine.dbs.compat.ADb.execOnConnection(ADb.java:163)
	at org.hortonmachine.dbs.h2gis.H2Db.getTables(H2Db.java:250)
	at org.hortonmachine.dbs.h2gis.H2GisDb.getTables(H2GisDb.java:254)
	at org.hortonmachine.dbs.h2gis.H2GisDb.getTablesMap(H2GisDb.java:283)
	at org.hortonmachine.dbs.compat.objects.DbLevel.getDbLevel(DbLevel.java:71)
	at org.hortonmachine.database.DatabaseController.gatherDatabaseLevels(DatabaseController.java:2089)
	at org.hortonmachine.database.DatabaseController.lambda$openRemoteDatabase$17(DatabaseController.java:1995)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: com.mchange.v2.resourcepool.CannotAcquireResourceException: A ResourcePool could not acquire a resource from its primary factory or source.
	at com.mchange.v2.resourcepool.BasicResourcePool.awaitAvailable(BasicResourcePool.java:1507)
	at com.mchange.v2.resourcepool.BasicResourcePool.prelimCheckoutResource(BasicResourcePool.java:644)
	at com.mchange.v2.resourcepool.BasicResourcePool.checkoutResource(BasicResourcePool.java:554)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool.checkoutAndMarkConnectionInUse(C3P0PooledConnectionPool.java:758)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool.checkoutPooledConnection(C3P0PooledConnectionPool.java:685)
	... 11 more
Caused by: org.h2.jdbc.JdbcSQLException: Connection is broken: "unexpected status 1162232148" [90067-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.engine.SessionRemote.done(SessionRemote.java:637)
	at org.h2.engine.SessionRemote.initTransfer(SessionRemote.java:132)
	at org.h2.engine.SessionRemote.connectServer(SessionRemote.java:447)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:332)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:124)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:103)
	at org.h2.Driver.connect(Driver.java:69)
	at com.mchange.v2.c3p0.DriverManagerDataSource.getConnection(DriverManagerDataSource.java:175)
	at com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:220)
	at com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:206)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.acquireResource(C3P0PooledConnectionPool.java:203)
	at com.mchange.v2.resourcepool.BasicResourcePool.doAcquire(BasicResourcePool.java:1176)
	at com.mchange.v2.resourcepool.BasicResourcePool.doAcquireAndDecrementPendingAcquiresWithinLockOnSuccess(BasicResourcePool.java:1163)
	at com.mchange.v2.resourcepool.BasicResourcePool.access$700(BasicResourcePool.java:44)
	at com.mchange.v2.resourcepool.BasicResourcePool$ScatteredAcquireTask.run(BasicResourcePool.java:1908)
	at com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread.run(ThreadPoolAsynchronousRunner.java:696)


Process Open database stopped at: 2021-11-09 11:50:43
~~~

Instead if I try to use `connect` button I can see PostGIS in the `Database type` dropdown but I cannot find where to write the server and the port parameters.

**Comment by moovida** [comment]
You are targetting an H2 database. The string for postgres would be something like:

```
jdbc:postgresql://localhost:5432/testgss
```

**Comment by lucadelu** [comment]
Thanks, sorry for the noise now it works

**Comment by moovida** [comment]
no problem
